opentera-webportal-service:
  image: introlab3it/opentera_webportal_service_dev
  restart: always
  ports:
    - "40075:40075"
  volumes:
    - opentera-db:/var/lib/postgresql
    - opentera-certificates:/opentera/teraserver/python/certificates
    - opentera-webportal-static:/opentera-webportal-service/static
    - opentera-webportal-config:/opentera-webportal-service/config
